### ISSUE TITLE
[FEATURE REQUEST] Add option to redirect only if match regex

### ISSUE THREAD

**Issue by SwiftWinds** [LorenzoPane/EvilScheme#12]
**Is your feature request related to a problem? Please describe.**
I’d like to redirect all Safari requests to Brave except websites with domain `invidio.us` (because background audio is limited to 30 seconds in all browsers except Safari)

**Describe the solution you'd like**
An option to input a regex (e.g., `http(s?):\/\/(?!(www\.)?invidio\.us).*`) that would have to be met for the request to redirect.

**Additional context**
Thanks for the great tweak! I can see that you put a lot of effort into the post, documentation, and issue-resolving that is unmatched by any other in the jailbreak community, at the low, low price of free! We are so thankful for your hard work. :)

**Comment by LorenzoPane** [comment]
Great idea! I've submitted 0.1.1 to Dynastic today to address some minor bugs and add some requested presets, but seeing this tweak used at scale has shown some limitations of Evil Kit in its current state (see #8, #9, #12). This evening, I'm going to look into a larger scale update, and I'll aim to push it out by this weekend.
Thanks for the kind words!
-L

**Comment by SwiftWinds** [comment]
Wow, thanks for the fast reply and progress. You don’t have to rush yourself, but I look forward to the improvements coming up! :)

**Comment by LorenzoPane** [comment]
Resolved as of 286ad731. Actions can now be ordered by priority, and redirection will be aborted if the url doesn't match any of the regexes.

**Comment by SwiftWinds** [comment]
Awesome! :D Thank you.

**Comment by SwiftWinds** [comment]
Just tested it. It works great! 👍
