### ISSUE TITLE
[PRESET REQUEST]Add geo: URL scheme in map presets

### ISSUE THREAD

**Issue by ghost** [LorenzoPane/EvilScheme#14]
**Preset destination**
Waze

**Preset target**
Apple Maps

**URL Scheme Info**
**geo:** instead of **maps:** are used throughout iOS default apps. Use both: `^(((http(s?)://)?maps.apple.com)|(maps:)|(geo:))`

**Comment by LorenzoPane** [comment]
Thanks for the information; I wasn't aware of that protocol. One question: am I correct that the `geo:` scheme only applies to latitude/longitude pairs? If so, it may be better to have a separate action for `^(geo:)`.

**Comment by ghost** [comment]
Oops, my mistake. After some debugging, I've failed to realise that EvilScheme redirects default apps regardless the regex.

Debugging proccess:
![905F84D6-90F6-4512-9C58-5427E21E928A](https://user-images.githubusercontent.com/66366194/83723308-114d1100-a671-11ea-8ec5-e2809e03a700.png)

![8BD47136-960F-491B-9A85-C9DB14E2D551](https://user-images.githubusercontent.com/66366194/83723323-16aa5b80-a671-11ea-9013-3b9af5f2d8b2.png)

Result:
`maps://maps.apple.com/maps?q=x.xxxxxx,xxx.xxxxxx`
![42B2D5ED-9C52-4A32-9E7C-4F9D804E3210](https://user-images.githubusercontent.com/66366194/83723452-4fe2cb80-a671-11ea-80cb-8977cdbc38a2.jpeg)
