### ISSUE TITLE
[PRESET REQUEST] Apple Maps

### ISSUE THREAD

**Issue by anonfox9** [LorenzoPane/EvilScheme#17]
**Preset destination**
The app you want links to open in. E.g. 

Apple Maps
**Preset target**
That app's stock counterpart. E.g. 

Google Maps

**URL Scheme Info**

I’m not sure if this is possible but please please please take a look been looking for this forever. When I use google in safari to find an address and click on the address it always opens google maps to show directions, I would like to just open Apple Maps. If possible I’d be so happy. Do you accept donations?

**Comment by LorenzoPane** [comment]
Are you talking about it being opened *within* safari or being opened in the Google Maps app?

**Comment by anonfox9** [comment]
No it opens the google maps app, I would like it to open Apple Maps instead. Here is a video.

https://streamable.com/iuqh2k

**Comment by anonfox9** [comment]
I’m not sure if the url is encoded normally sadly, but I’ve been looking for this forever

**Comment by anonfox9** [comment]
It used to open up Apple Maps but google changed something and now it either opens up inside safari if you don’t have google maps or in google maps if you have the app downloaded

**Comment by hydrometer** [comment]
Divesting from google and I’d like to open all google maps links in Apple Maps.

**Comment by git-anish** [comment]
@LorenzoPane I was going to suggest something similar (wanted to use Waze rather than A.M.), I tried making this following your manual but I suspect that google is using non-standard URL schemes to achieve this

Any tips on how to get this done?

**Comment by LorenzoPane** [comment]
@git-anish If you have the time, can try to make something analogous to the translation from [here](https://github.com/LorenzoPane/EvilScheme/blob/8b7af8db4016b7d2a22edbc34d3b9714d00c81f2/Prefs/src/EVSPreferenceManager.m#L258) and [here](https://github.com/LorenzoPane/EvilScheme/blob/8b7af8db4016b7d2a22edbc34d3b9714d00c81f2/Prefs/src/EVSPreferenceManager.m#L287). Both Google Maps and Waze are reasonably well documented by google [here](https://developers.google.com/maps/documentation/urls/ios-urlscheme) and [here](https://developers.google.com/waze/deeplinks/), respectively. You could probably get away with just forwarding `q` to `q`, `ll` to `ll`, and `daddr` to `q`. Let me know if you need more help. And yeah, I should probably put more time into making the manual more usable / exhaustive.

**Comment by LorenzoPane** [comment]
I'm going to close this issue as wontfix for now, because I don't want the built in preset list to turn from a list of `x` destinations to a list of `x  *  y` destinations for each target. At some point I would like to make presets more organizable, savable, and sharable and at that point I may be more receptive to adding more presets (particularly if I'm not liable for their quality). However, again, let me know if any of you want help fitting the tool to your individual use case.

**Comment by git-anish** [comment]
Hey Lorenzo,

Thanks for pointing me to those docs!

I've created a similar translation for this purpose, its able to open Waze but not open the addresses within Waze correctly. Should I be excluding the parameters that won't be translated?

**Comment by LorenzoPane** [comment]
I don't think excess parameters passed to waze would interfere with the address opening, but it can't hurt. I can't really troubleshoot without knowing what the result was, so try comparing the output url in the `Log` section to examples provided in the Waze docs or outputs from my Apple->Waze preset.

**Comment by git-anish** [comment]
I took a look at the Apple > Waze log (copied), and it shows a clear Payload and how its being translated.

I'm not sure the same is true for Google Maps's Payload, I'm unclear if its being recorded correctly in the log. Thoughts?

I've copied below the log showing normal GMaps operation and the modified GMaps > Waze output

**GMaps operation**

Ignored: com.google.Maps
<FBSOpenApplicationOptions: 0x2806f3720> {
    __BrowserAppLinkState4LS = {
        browserReuseTab = 1;
    }
    __PayloadOptions = {
        UIApplicationLaunchOptionsSourceApplicationKey = com.apple.mobilesafari;
    }
    __UserActivity4LS = 1;
    __Actions = {
        <UIActivityContinuationAction: 0x282b6f900> {
            handler = none;
            info = <BSSettings: 0x28027b800> {
                activityType = NSUserActivityTypeBrowsingWeb;
                (5) = NSUserActivityTypeBrowsingWeb;
                (6) = 2020-06-17 13:25:21 +0000;
                userActivityData = {length = 1358, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000045a };
            };
        };
    }
    __AppLink4LS = <_LSSharedWebCredentialsAppLink: 0x2821d5b00>;
}


**GMaps > Waze**

From: com.google.Maps
<FBSOpenApplicationOptions: 0x2806c13f0> {
    __BrowserAppLinkState4LS = {
        browserReuseTab = 1;
    }
    __PayloadOptions = {
        UIApplicationLaunchOptionsSourceApplicationKey = com.apple.mobilesafari;
    }
    __UserActivity4LS = 1;
    __Actions = {
        <UIActivityContinuationAction: 0x282894480> {
            handler = none;
            info = <BSSettings: 0x280462680> {
                activityType = NSUserActivityTypeBrowsingWeb;
                (5) = NSUserActivityTypeBrowsingWeb;
                (6) = 2020-06-17 13:27:30 +0000;
                userActivityData = {length = 1358, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000045a };
            };
        };
    }
    __AppLink4LS = <_LSSharedWebCredentialsAppLink: 0x2821fa5e0>;
}

To: com.waze.iphone
<FBSOpenApplicationOptions: 0x2806c13f0> {
    __PayloadOptions = {
        UIApplicationLaunchOptionsSourceApplicationKey = com.apple.mobilesafari;
    }
    __PayloadURL = waze://?;
}


**Apple > Waze**

From: com.apple.Maps
<FBSOpenApplicationOptions: 0x2806ca520> {
    __PayloadOptions = {
        UIApplicationLaunchOptionsSourceApplicationKey = com.apple.mobilesafari;
    }
    __PayloadURL = mapitem://YnBsaXN0MDDSAQIDEF8QJU1LTWFwSXRlbUxhdW5jaEFkZGl0aW9uc0xhdW5jaE9wdGlvbnNfECBNS01hcEl0ZW1MYXVuY2hBZGRpdGlvbnNNYXBJdGVtc9YEBQYHCAkKCwwNDg9fEB1NS0xhdW5jaE9wdGlvbnNEaXJlY3Rpb25zTW9kZV8QJ01LTGF1bmNoT3B0aW9uc1Nlc3Npb25TZXF1ZW5jZU51bWJlcktleV8QJU1LTGF1bmNoT3B0aW9uc1Nlc3Npb25DcmVhdGlvblRpbWVLZXlfECRNS0xhdW5jaE9wdGlvbnNSZWZlcnJhbElkZW50aWZpZXJLZXlfEB9NS0xhdW5jaE9wdGlvbnNTZXNzaW9uSURIaWdoS2V5XxAeTUtMYXVuY2hPcHRpb25zU2Vzc2lvbklETG93S2V5XxAkTUtMYXVuY2hPcHRpb25zRGlyZWN0aW9uc01vZGVEZWZhdWx0EgBSNNojQSTain/F3/xfEBZjb20uYXBwbGUubW9iaWxlc2FmYXJpFAAAAAAAAAAA/TYtEXGmca8UAAAAAAAAAADsTYfdRWfrM6ER0RITXxATTUtNYXBJdGVtR0VPTWFwSXRlbU8RCCsKqBAIp+OTxOGW3puGARAAIuAECAEQACDA0QIoADABOr4BCghjb20ueWVscBIWeHZwMUdtS1ctTEFsbHFMNUlZdzJldyIleWVscDUuMzovLy9iaXoveHZwMUdtS1ctTEFsbHFMNUlZdzJldyIjeWVscDQ6Ly8vYml6L3h2cDFHbUtXLUxBbGxxTDVJWXcyZXciInllbHA6Ly8vYml6L3h2cDFHbUtXLUxBbGxxTDVJWXcyZXciKmh0dHA6Ly95ZWxwLmNvbS9iaXoveHZwMUdtS1ctTEFsbHFMNUlZdzJld0LUAgrRAgg5EgwrMTQxNjUxNjkwNDAyGGh0dHA6Ly9vdXRwb3N0Y29mZmVlLmNvbVIgCgVlbi1VUxoXT3V0cG9zdCBDb2ZmZWUgUm9hc3RlcnNaIAoFZW4tVVMaF091dHBvc3QgQ29mZmVlIFJvYXN0ZXJzYhQIARoKCgJlbhoERm9vZCIEZm9vZGIrCAIaFQoCZW4aD0NvZmZlZSBSb2FzdGVyeSIQY29mZmVlcm9hc3Rlcmllc2IrCAIaFQoCZW4aD0NvZmZlZSBSb2FzdGVyeSIQY29mZmVlcm9hc3Rlcmllc2IrCGMaFQoCZW4aD0NvZmZlZSBSb2FzdGVyeSIQY29mZmVlcm9hc3Rlcmllc4gBAZABAJgBAcoBEgoECAYQCAoECAQQYgoECAoQANIBCmZvb2Rkcmlua3PaARVmb29kLmNvZmZlZXJvYXN0ZXJpZXPgAQBaOAiuTRIkZWE2NDUyNDMtZDRiOC00MzdhLWE2Y2MtYjk2ZWQ1MDk3YzQwGg0xNTkwMzA2OTUxMDgzYAIivAQIBRAAIMDRAigAMAFC8QMq7gMKvwEKAmVuGrgBWg8xNTc4IEJsb29yIFN0IFdaElRvcm9udG8gT04gTTZQIDFBNFoGQ2FuYWRheogBCgZDYW5hZGESAkNBGgdPbnRhcmlvIgJPTioHVG9yb250bzIHVG9yb250bzoHTTZQIDFBNEIPSGlnaCBQYXJrIE5vcnRoUgpCbG9vciBTdCBXWgQxNTc4Yg8xNTc4IEJsb29yIFN0IFeKAQtPbGQgVG9yb250b4oBD0hpZ2ggUGFyayBOb3J0aBJUCgVlbi11cxpLG1x0bj1hZGRyZXNzXCAxNTc4IBtcdG49bm9ybWFsXCAbXHRvaT1saHBcICdibE9SK18nc3RSK2l0Xyd3RXN0IBtcdG9pPW9ydGhcGtMBCgJlbhrMAQoGQ2FuYWRhEgZDYW5hZGEaB09udGFyaW8iB09udGFyaW8qB1Rvcm9udG8yB1Rvcm9udG9CD0hpZ2ggUGFyayBOb3J0aFIRQmxvb3IgU3RyZWV0IFdlc3RaHxtcdG49YWRkcmVzc1wgMTU3OCAbXHRuPW5vcm1hbFxiMRtcdG49YWRkcmVzc1wgMTU3OCAbXHRuPW5vcm1hbFwgQmxvb3IgU3RyZWV0IFdlc3SKAQtPbGQgVG9yb250b4oBD0hpZ2ggUGFyayBOb3J0aFo4CK5NEiRlYTY0NTI0My1kNGI4LTQzN2EtYTZjYy1iOTZlZDUwOTdjNDAaDTE1OTAzMDY5NTEwODNgAiKOAQgCEAAgwNECKAAwAUIpEicKEgn/VezUAdRFQBHlaa/0EN1TwCIRCg9BbWVyaWNhL1Rvcm9udG9KBWFwcGxlSgZwbGFjZXNKA3BvaUoDRVNUUAFaOAiuTRIkZWE2NDUyNDMtZDRiOC00MzdhLWE2Y2MtYjk2ZWQ1MDk3YzQwGg0xNTkwMzA2OTUxMDgzYAIibwhAEAAgwNECKAAwAUIlggQiChYIAggDCAQIBQgGCAcSCAiA4QEQkN4DMAE6BgiIDhCQHFo4CK5NEiRlYTY0NTI0My1kNGI4LTQzN2EtYTZjYy1iOTZlZDUwOTdjNDAaDTE1OTAzMDY5NTEwODNgAiKeAggGEAAgwNECKAAwAjq+AQoIY29tLnllbHASFnh2cDFHbUtXLUxBbGxxTDVJWXcyZXciJXllbHA1LjM6Ly8vYml6L3h2cDFHbUtXLUxBbGxxTDVJWXcyZXciI3llbHA0Oi8vL2Jpei94dnAxR21LVy1MQWxscUw1SVl3MmV3IiJ5ZWxwOi8vL2Jpei94dnAxR21LVy1MQWxscUw1SVl3MmV3IipodHRwOi8veWVscC5jb20vYml6L3h2cDFHbUtXLUxBbGxxTDVJWXcyZXdCGDIWCAERAAAAAAAAEkAZAAAAAAAAFEAgSEIWMhQIAxEAAAAAAAAAQBkAAAAAAAAQQFobCJFOEhZ4dnAxR21LVy1MQWxscUw1SVl3MmV3YAIiJQgQEAAgwNECKAAwAUIVggESCgQIBBBiCgQIBhAICgQIChAAYAIiyQEIJRAAIMDRAigAMAFCuAGqArQBCrEBaHR0cHM6Ly9tYXBzLmFwcGxlLmNvbS9wbGFjZT9xPU91dHBvc3QlMjBDb2ZmZWUlMjBSb2FzdGVycyZhdWlkPTk2NzEzMzE0NDgyOTIxNzYyOTUmYWRkcmVzcz0xNTc4JTIwQmxvb3IlMjBTdCUyMFcsJTIwVG9yb250byUyME9OJTIwTTZQJTIwMUE0LCUyMENhbmFkYSZsbD00My42NTYzMDU5LC03OS40NTQxNTk5YAIiDggnEAAgwNECKAAwAGACIg4IKBAAIMDRAigAMABgAiIOCDQQACDA0QIoADAAYAIork06JwolCKfjk8Thlt6bhgESEgn/VezUAdRFQBHlaa/0EN1TwBiuTZADAUDO35ORiigACAANADUAWABlAIUArwDXAP4BIAFBAWgBbQF2AY8BoAGxAbMBtgHMAAAAAAAAAgEAAAAAAAAAFAAAAAAAAAAAAAAAAAAACfs=;
}

To: com.waze.iphone
<FBSOpenApplicationOptions: 0x2806ca520> {
    __PayloadOptions = {
        UIApplicationLaunchOptionsSourceApplicationKey = com.apple.mobilesafari;
    }
    __PayloadURL = waze://?q=%4F%75%74%70%6F%73%74%20%43%6F%66%66%65%65%20%52%6F%61%73%74%65%72%73%20%31%35%37%38%20%42%6C%6F%6F%72%20%53%74%20%57%20%54%6F%72%6F%6E%74%6F%2C%20%4F%4E%20%4D%36%50%20%31%41%34;
}

**Comment by LorenzoPane** [comment]
Ah. That's this somewhat irritating way that URLs are sometimes passed nested in that `userActivityData`. I should update the logging function to include buried URLs. As hacky of a workaround as this is, you could temporarily write an action that translates the `.*` regex to a full-url portion to see what the original was supposed to be in the log.

**Comment by git-anish** [comment]
I believe I was able to see the URLs using your recommendation

Am I using the correct syntax here?

^(((http(s?)://)?((maps\.google\.{TLD}/) | ((www\.)?google\.{TLD}/maps/) | ((maps.app.goo.gl/) | (goo.gl/maps/)) .* | (comgooglemaps:) | (comgooglemapsurl:))


for some reason the translated queries are still not being sent to Waze, even though I can now finally see the translation correctly

I've attached my latest log & pref.plist here

[Archive.zip](https://github.com/LorenzoPane/EvilScheme/files/4886304/Archive.zip)
