### ISSUE TITLE
Apollo preset issues

### ISSUE THREAD

**Issue by KairuByte** [LorenzoPane/EvilScheme#2]
I haven’t had time to look into the root cause or the correction, but the Apollo preset has a few issues.

- Clicking the reddit image at the top when in google amp results in Apollo errors because the URL gets mangled.
- Clicking “open in app” results in opening Apollo, but no change in navigation, this happens both directly on a Reddit page, and when in google amp.

**Comment by LorenzoPane** [comment]
Yeah I'm gonna take a look at improving the preset. I think it is an issue with IPC calls using AMP URLs.
