### ISSUE TITLE
[BUG] Spolight Search Engine not compatible with Microsoft Edge

### ISSUE THREAD

**Issue by imReker** [LorenzoPane/EvilScheme#22]
**Describe the bug**
Spolight Search Engine not compatible with Microsoft Edge, due to mailformed url.

**To Reproduce**
0.Set Edge as default browser.
1.Set a spolight search engine, eg, Google.
2.Search something in spolight.
3.Edge try to load https://https://google.com/search?q%3D

Double scheme `https`, and the rest of url is encoded (`=` became `%3D`)

**Extra Info**
Please include
1. iPhone XR
2. 13.5
3. 0.1.1

**Comment by LorenzoPane** [comment]
Resolved in e580fa63.

**Comment by imReker** [comment]
Amazing, thanks a lot, waiting for deb update on repo.
