### ISSUE TITLE
[FEATURE REQUEST] Custom spolight search engine

### ISSUE THREAD

**Issue by imReker** [LorenzoPane/EvilScheme#23]
Currently other search engine(eg, baidu) is not supported, a simple way is add a textbox and let users input `url` and `{search}` manually, eg, `https://m.baidu.com/s?word={search}`.

BTW, users can edit the plist of EvilScheme to archieve this in v0.1.1

**Comment by LorenzoPane** [comment]
Resolved in e580fa63
