### ISSUE TITLE
[BUG] Target bundle IDs disappear when leaving settings, only one stays

### ISSUE THREAD

**Issue by ghost** [LorenzoPane/EvilScheme#26]
**Describe the bug**
When I add multiple target bundle IDs for an app, after leaving the EvilScheme settings and going back, the bundle IDs all disappear except for one of them. They all continue to work until I click "Apply" in the settings again, which actually makes the now disappeared bundle IDs stop redirecting .

**To Reproduce**
1. Add an entry for an app (for example try the Zebra preset)
2. Set multiple target bundle IDs
3. Leave EvilScheme settings completely
4. Return to EvilScheme settings and open the entry you added
5. See that only one of the target bundle IDs is there

**Expected behavior**
All the target bundle IDs should stay.

**Extra Info**
1. Device model: iPhone XR
2. iOS version: iOS 13.3
3. Evil Scheme version: 0.2.1

**Comment by LorenzoPane** [comment]
Another silly mistake on my part! It is fixed now, but I'm going to hold off on pushing it to Dynastic Repo until later today in case there are more 0.2.1 bug reports in the next couple hours.
