### ISSUE TITLE
[FEATURE REQUEST] Change default browser also for home shortcuts

### ISSUE THREAD

**Issue by antoniomcr96** [LorenzoPane/EvilScheme#29]
If I add a shortcut to home with Safari, it will open with Safari. Is it possible to change this behavior with evil scheme ? Is there any prefix I can use?
Thanks in advance

**Comment by LorenzoPane** [comment]
Duplicate of #25

**Comment by antoniomcr96** [comment]
> Duplicate of #25

Sorry, I didn’t see. Thank you for the awesome work. Ciao!
