### ISSUE TITLE
Direct navigation to web URL bypasses EvilScheme

### ISSUE THREAD

**Issue by KairuByte** [LorenzoPane/EvilScheme#3]
This may very well be intentional (or an existing limitation within iOS), but if you directly navigate to a URL (type it by hand or paste) , the browser will simply navigate to the web page.

I found this while testing Apollo defined schemes.

**Comment by LorenzoPane** [comment]
Do you mean paste into the Safari URL bar? If so, this is intended behavior and will not be changed.

**Comment by KairuByte** [comment]
Yes that was the use case I was speaking of, though Chrome instead of Safari.

**Comment by LorenzoPane** [comment]
Yeah, I have no intention of changing that. Thanks for the feedback, though! :)
