### ISSUE TITLE
[PRESET REQUEST] Twitter

### ISSUE THREAD

**Issue by ctrlcmdshft** [LorenzoPane/EvilScheme#30]
**Preset destination**
Tweetbot - com.tapbots.Tweetbot4

**Preset target**
Twitter - com.atebits.Tweetie2

**URL Scheme Info**
Not sure on this one

**Comment by compilingEntropy** [comment]
This one is pretty easy.

URL Scheme: https://tapbots.net/tweetbot3/support/url-schemes/
(Tweetbot4 has the same scheme as Tweetbot3)

I’ve been running the following for a week or two and it works for the main things, although it may need more testing.

Actions:
1:
Regex: `.*twitter.com/[^/]+/?$`
Blueprint:
- Text: `tweetbot://`
- Path
- Text: `/user_profile/`
- Path

2:
Regex: `.*twitter.com.*`
Blueprint:
- Text: `tweetbot://`
- Path

**Comment by ctrlcmdshft** [comment]
Thank you so far so good working as intended

**Comment by LorenzoPane** [comment]
Hi, great work! Has tweetbot 4 been taken off the app store? I can't seem to find it. I bought tweetbot 5 to test, but I'm unable to get those schemes to work :/. I'd like to include this once I can confirm it is working.

**Comment by ctrlcmdshft** [comment]
Tweetbot 5 is the current version and still uses com.tapbots.Tweetbot4 it was done that way to get around some twitter changes for 3rd party apps

**Comment by LorenzoPane** [comment]
Aha I see. Thanks! I also ended up getting the scheme to work; I think I was misreading the documentation. I'll push an official preset this weekend :)

**Comment by ctrlcmdshft** [comment]
After testing some this isn’t fully working like I thought if you go to this link https://www.reddit.com/r/jailbreak/comments/cs29co/comment/exc288g  on phone then click link in thread it opens Tweetbot but doesn’t open to tweet

**Comment by LorenzoPane** [comment]
Does it work better after 64e94ea5?

**Comment by ctrlcmdshft** [comment]
How do I test that to see

**Comment by LorenzoPane** [comment]
I'm away from a computer, so I can't build a deb for you, but if you want to add it manually:

```
Action 1
--------
regex: ".*twitter.com/[^/]+/?$"
outline: [
    Constant String: "tweetbotbot:///user_profile/"
    Path
]

Action 2
--------
Regex: ".*twitter.com/i/lists/.*$"
outline:[
    Constant string: "tweetbot:///list/"
    Regex Substitution
        Regex: "^.*/i/lists/(\\d+).*$"
        Template:@"$1"
]

Action 3
--------
Regex: ".*twitter.com/.+/status/.*$"
Outline: [
    Constant String: "tweetbot:///status/" percentEncodingIterations:0],
    Regex Substitution
        Regex: "^.*/[^/]+/status/(\\d+).*$"
        Template: "$1"
]

Action 4
--------
Regex: ".*twitter.com.*"
Outline: [
    Constant String: "tweetbotbot:///"
    Path
]
```
All have 0 percent encoding iterations

**Comment by compilingEntropy** [comment]
> After testing some this isn’t fully working like I thought if you go to this link https://www.reddit.com/r/jailbreak/comments/cs29co/comment/exc288g  on phone then click link in thread it opens Tweetbot but doesn’t open to tweet

I am not able to reproduce; the link you specified does open the tweet in tweetbot for me using the settings I originally posted. It looks like the configuration that @LorenzoPane posted above is a bit more comprehensive though, so I suspect we’ll all get better results with that.

**Comment by DimitarNestorov** [comment]
Do you know what the actions should be to open the official Twitter app?
