### ISSUE TITLE
opens Tweetbot but doesn’t open to tweet

### ISSUE THREAD

**Issue by ctrlcmdshft** [LorenzoPane/EvilScheme#31]
After testing some this isn’t fully working like I thought if you go to this link https://www.reddit.com/r/jailbreak/comments/cs29co/comment/exc288g  on phone then click link in thread it opens Tweetbot but doesn’t open to tweet

_Originally posted by @ctrlcmdshft in https://github.com/LorenzoPane/EvilScheme/issues/30#issuecomment-646775506_

**Comment by LorenzoPane** [comment]
Re-opening the old thread and closing this one as a duplicate
