### ISSUE TITLE
Evil Scheme on iOS 11 PLEASE. Happy to pay!

### ISSUE THREAD

**Issue by gititwhileyoucan** [LorenzoPane/EvilScheme#36]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by LorenzoPane** [comment]
Closing as duplicate of #5. I'm still unsure wether I'll backport, but if I do, I'll target both iOS 11 and 12.

**Comment by gititwhileyoucan** [comment]
Thanks for writing sir! And if you decide to backport, I'm happy to help test for you. Cheers, Ric
________________________________
