### ISSUE TITLE
[BUG] spotlight search web stuck on duckduckgo as search engine

### ISSUE THREAD

**Issue by xconny** [LorenzoPane/EvilScheme#42]
Spotlight search is stuck on duckduckgo, i’ve tried changing in ‘experimental settings’ back to google and it wont change. The only thing thar gets spotlight search web back to google for the search engine is disabling this tweak.

**Comment by LorenzoPane** [comment]
After choosing the search engine you would like, delete and re-add your web browser then click apply. Feel free to re-open the issue if this doesn’t work.
