### ISSUE TITLE
[FEATURE REQUEST] iOS 11 & 12 Support

### ISSUE THREAD

**Issue by Randomblock1** [LorenzoPane/EvilScheme#5]
**Describe the bug**
Selecting the EvilScheme settings in Settings results in a freeze for about 5 seconds, followed by Settings closing.

**To Reproduce**
1. Be on iOS 12.4.5
2. Try to open EvilScheme settings 

**Expected behavior**
It doesn’t crash.

**Extra Info**
1. iPhone 6
2. iOS 12.4.5
3. Evil Scheme 0.1.0
4. Crash report (if applicable): Settings crash does not actually produce a crash log for some reason. I wish it did.

**Comment by LorenzoPane** [comment]
I'm not currently actively supporting iOS 12. I goofed up in the submission process and didn't properly specify that in the depends. Future support isn't out of the picture, but I don't have an iOS 12 device to test with.
