### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HYPExMon5ter** [LorenzoPane/EvilScheme#7]
**Describe the bug**
Firefox doesn’t open when I click on links even though I have Firefox as my default browser.

**To Reproduce**
1. Make Firefox your default browser
2. Click on a link

**Expected behavior**
When I click on a link it should open Firefox, not Safari

**Screenshots**
![DDF44B67-718D-4D30-83DD-88A1848E051F](https://user-images.githubusercontent.com/12315186/83487348-e39d7780-a478-11ea-9230-8a228603b485.png)

**Extra Info**
1. Device model: iPhone XS
2. iOS version: 13.5
3. Evil Scheme version: 0.1.0

**Comment by LorenzoPane** [comment]
Thanks for the bug report. Just to clarify, have you applied your settings by pressing the `Save` button on the top right corner of the primary preference pane?

**Comment by HYPExMon5ter** [comment]
I’m pretty sure but I’ll try again.

**Comment by HYPExMon5ter** [comment]
So aparently I didn’t, clicked save and it started working. However, upon
clicking links in gmail it opens up the browser inside gmail (safari), is
there a way to open up Firefox instead?

**Comment by LorenzoPane** [comment]
The correct browser should be opened when you tap the safari icon in the bottom right corner of internal browsers.
