### ISSUE TITLE
[BUG] Zebra preset is not working

### ISSUE THREAD

**Issue by terry3041** [LorenzoPane/EvilScheme#8]
**Describe the bug**
The Zebra preset is not working after chosen and saved.
A respring does not help too.

**To Reproduce**
1. Choose the Zebra preset
2. Save
3. Press on "Add to Cydia" link

**Expected behavior**
It should open Zebra instead of an invalid URL alert.

**Extra Info**
Please include
1. Device model: iPhone XS
2. iOS version: 13.5
3. Evil Scheme version: 0.1.0

**Comment by LorenzoPane** [comment]
Thanks for the bug report. Can you clarify what you mean by "invalid URL alert"? Are any apps launched after clicking on an "Add to Cydia" link?

**Comment by terry3041** [comment]
No apps are launched after clicking.
And I have Cydia uninstalled btw.
The alert look like this.
![4454DB3F-A946-4B22-9AF9-1BD206AC10D9](https://user-images.githubusercontent.com/19218518/83534851-ef924380-a523-11ea-8cb9-433b181ae678.png)

**Comment by LorenzoPane** [comment]
Aha, that would be why. This tweak relies on redirecting requests from one app to another, and the Zebra preset targets Cydia. Do you have Sileo installed? If so, changing the `Old` Bundle ID from `com.saurik.Cydia` to `org.coolstar.SileoStore` should work.

**Comment by LorenzoPane** [comment]
Assuming that was the solution, I'm going to look into allowing multiple target Bundle ID's in a single preset in the next Evil Kit update.

**Comment by terry3041** [comment]
I just have Zebra installed.
So I cant change my default package manager without installing the others?

**Comment by LorenzoPane** [comment]
As of now, yes. I'm looking into ways to change this in a future release, but it is low priority.

**Comment by terry3041** [comment]
I am looking forward to the implementation of that feature. Thanks for your work!
